### ISSUE TITLE
Naming refactoring

### ISSUE THREAD

**Issue by deksden** [Abdizriel/nodejs-microservice-starter#12]
IMHO, some naming refactoring makes this starter project a little bit cleanier: 

xxx.model --> xxx.schema
xxx.dao --> xxx.model

Anyone who knows mongoose will feel schema/model more comfortable. Model/dao is a little bit exotic.

Indeed, i really like code style!

**Comment by Abdizriel** [comment]
@deksden Yes, I agree with you and I had it in mind to change it.

but I will follow this schema:

index.js
index.spec.js
xxx.controller.integration.js
xxx.controller.js
xxx.model.js
xxx.model.spec.js

Where xxx.model would stay as model and xxx.dao actions would be moved to xxx.controller

**Comment by deksden** [comment]
Really interested to see this in code)

**Comment by Abdizriel** [comment]
Enhancement merged to development in #13
