### ISSUE TITLE
Env config

### ISSUE THREAD

**Issue by deksden** [Abdizriel/nodejs-microservice-starter#8]
IMHO, using dotenv and dotenv-safe modules for configuring environment is much easier than building/maintaining own solution in server/config/index.js. Its as simple as

    import dotenv from 'dotenv-safe'
    ...
    dotenv.load()

All stuff goes into process.env and never overwrite variables already set externally. So, its ok for CI/Docker, etc.

Just look at https://github.com/rolodato/dotenv-safe

**Comment by Abdizriel** [comment]
@deksden Thanks for info. I will take a look on that.

**Comment by Abdizriel** [comment]
Enhancement was done in #11
